name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Remove __pycache__ directory
      run: sudo rm -rf __pycache__

    - name: Move data files out of repository
      run: |
        sudo mkdir -p /tmp/data
        sudo mv attendance.txt hourtotals.txt hourtotals.csv /tmp/data/ || true

    - uses: actions/checkout@v2

    - name: Move data files back into repository
      run: |
        sudo mv /tmp/data/* . || true

    - name: Stop Gunicorn server and remove screen
      run: |
        sudo screen -X -S gunicorn quit || true

    - name: Start Gunicorn server in a new screen
      run: |
        cd $GITHUB_WORKSPACE
        ls
        sudo screen -dmS gunicorn sudo gunicorn -w $(nproc) -k gthread --threads 2 -b 0.0.0.0:80 --timeout 6000 app:app
