name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Stop Gunicorn server and remove screen
      run: |
        sudo screen -X -S gunicorn quit || true

    - name: Start Gunicorn server in a new screen
      run: |
        cd $GITHUB_WORKSPACE
        ls
        sudo screen -dmS gunicorn sudo gunicorn -w 2 -b 0.0.0.0:80 --timeout 6000 app:app
